// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzdjbikaepxspnvywdct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6ZGpiaWthZXB4c3Budnl3ZGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzg1MDIsImV4cCI6MjA2NzcxNDUwMn0.SNfMQhvTGcGMWzO6wWZJhCdFIU9Stw4Bxn_-_faCY14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});